[package]
name = "gooool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { version = "5.0" }
ndarray = { version = "0.15.6" }
itertools = { version = "0.13.0" }
